# Configuración de golangci-lint
run:
  modules-download-mode: readonly
  go: '1.24'
  path: ["./cmd/...", "./internal/...", "./pkg/..."]
  allow-parallel-runners: true

# Añadir esta nueva sección
issues:
  exclude-dirs:
    - run

linters-settings:
  errcheck:
    check-type-assertions: true

linters:
