apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-vault-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vault-busybox.labels" . | nindent 4 }}
    component: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.vault.storage.size }}
  storageClassName: {{ .Values.vault.storage.storageClass }}