apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vault
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vault-busybox.labels" . | nindent 4 }}
    component: vault
spec:
  selector:
    {{- include "vault-busybox.selectorLabels" . | nindent 4 }}
    component: vault
  ports:
    - port: {{ .Values.vault.ports.http }}
      targetPort: http
      name: http
    - port: {{ .Values.vault.ports.cluster }}
      targetPort: cluster
      name: cluster
  type: NodePort # Change from LoadBalancer to NodePort for local environments like Minikube