apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-busybox-ssh
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vault-busybox.labels" . | nindent 4 }}
    component: busybox-ssh # Differentiate from the main busybox component if needed
spec:
  type: NodePort # Change from LoadBalancer to NodePort
  selector:
    {{- include "vault-busybox.selectorLabels" . | nindent 4 }}
    component: busybox # Selects the busybox pods
  ports:
    - name: ssh
      protocol: TCP
      port: 2222 # External port the LoadBalancer will listen on
      targetPort: ssh # Name of the port defined in the busybox deployment container spec
